Math magicians: components
Rn486/Math-Magicians pull request #2
Opened 2022-09-15 21:07 UTC by Rn486

### **Math magicians: components**

In this pull request, I have-; 

- Deleted all the boilerplate from CRA (text, images, styles).
- Created a directory called components.
- Inside components, I created a new Calculator.js file.
- In Calculator.js, I created a React component that matches the provided design
- Used class-based components.

2022-09-15 21:27 UTC, roshan-bajgain requested changes
Hi @Rn486, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 21:27 UTC, roshan-bajgain commented on src/components/calculator.js
> +      </thead>
- [ ] According to the project requirement, the Calculator.js component should be class-based. Please implement it

2022-09-15 21:27 UTC, roshan-bajgain commented on src/App.js
- [ ]  According to the project requirement, the App.js component should be class-based. Please implement it. eg:
`
class App extends Component {
  render() {
    return {
      <Calculator />
    };
  }
}
`

2022-09-15 21:27 UTC, roshan-bajgain commented on src/App.css
> +  background-color: #ff7518;
- [ ] Please implement the vertical border between the number and kindly check the font family as well.
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/190511607-2c894f16-46ae-4803-aec5-ec93bf855683.png)
### Your design
![your](https://user-images.githubusercontent.com/81727988/190511631-657e4257-737f-458b-8421-fa538e8ec0bb.png)

2022-09-16 01:26 UTC, mateo951 approved these changes
### Hi @Rn486, 

Well done making the changes requested by the previous reviewer 🐐
Your project is complete!  There is nothing else to say other than... it's time to merge it 🐐 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 01:26 UTC, mateo951 commented on src/App.js
> +class App extends React.PureComponent {
Addressed 🚀

2022-09-16 01:27 UTC, merged